linters:
  disable-all: true
  enable:
  - gocritic
  - gofmt
  - gosimple
  - govet # Includes fieldalignment for struct memory optimization
  - ineffassign
  - misspell
  - revive
  - staticcheck
  - typecheck
  - unparam
  - unused
  - mnd
  - copyloopvar
  - errcheck # Check for unchecked errors
  - gocyclo # Check for code complexity
  - prealloc # Check for preallocation of slice capacity

linters-settings:
  depguard:
    rules:
      dashboard-ui:
        files:
        - internal/ui/**/*.go
        deny:
        - pkg: fmt
          desc: "use logger package for output in dashboard UI"
  gocritic:
    enabled-tags:
    - diagnostic
    - style
    - performance
    disabled-checks:
    - hugeParam # Disable hugeParam check as it's not relevant for our UI components
    - evalOrder # Disable evalOrder as it conflicts with our command pattern
    - singleCaseSwitch # Allow single case switches for type assertions
    - sloppyTypeAssert # Disable sloppy type assertions check
  mnd:
    ignored-numbers:
    - '0o644' # Common file permission
    - '0o755' # Common file permission
    - '2' # Common UI layout divisor
    - '4' # Common UI padding/margin
    - '6' # Common UI padding/margin
    - '10' # Common timeouts and sizes
    - '20' # Common UI spacing
    - '100' # Common percentage calculations
    ignored-files:
    - 'internal/ui/widgets/sysinfo/widget.go'
    - 'internal/ui/styles/styles.go'
    - 'internal/testutil/testlogger/logger.go'
  revive:
    rules:
    - name: unused-parameter
      disabled: true # Disable unused parameter check as it's too strict for our interfaces
    - name: unexported-return
      disabled: true # Allow unexported return types in test utilities
    - name: exported
      disabled: false # Keep exported symbol documentation check

issues:
  exclude-use-default: false
  max-per-linter: 0
  max-same-issues: 0
  exclude-dirs:
  - build/
  - coverage/
  exclude-rules:
  - path: _test\.go
    linters:
    - unused-parameter # Don't check unused parameters in tests
    - gocritic # Don't run gocritic on tests

output:
  formats:
  - format: colored-line-number

telemetry:
  enabled: true # Enable telemetry to help Go improve
