repos:
- repo: https://github.com/golangci/golangci-lint
  rev: v1.62.2
  hooks:
  - id: golangci-lint
    name: golangci-lint
    entry: golangci-lint run
    types: [ go ]
    language: golang
    pass_filenames: false
