version: '3'

vars:
  BINARY_NAME: dashboard
  BUILD_DIR: build
  COVERAGE_DIR: coverage

tasks:
  default:
    cmds:
    - task --list-all
    silent: true

  install-tools:
    desc: Install development tools
    cmds:
    - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
    - go install golang.org/x/tools/cmd/goimports@latest
    - go install github.com/google/wire/cmd/wire@latest

  lint:
    desc: Run golangci-lint
    deps: [ wire ]
    cmds:
    - golangci-lint run ./...

  fmt:
    desc: Format code
    cmds:
    - gofmt -s -w .
    - goimports -w .

  test:
    desc: Run tests with coverage
    deps: [ wire ]
    cmds:
    - powershell New-Item -ItemType Directory -Force -Path {{.COVERAGE_DIR}}
    - go test -race -coverprofile={{.COVERAGE_DIR}}/coverage.out -covermode=atomic ./...
    - go tool cover -html={{.COVERAGE_DIR}}/coverage.out -o {{.COVERAGE_DIR}}/coverage.html

  build:
    desc: Build the application
    deps: [ wire ]
    cmds:
    - powershell New-Item -ItemType Directory -Force -Path {{.BUILD_DIR}}
    - go build -o {{.BUILD_DIR}}/{{.BINARY_NAME}}.exe ./cmd/dashboard

  run:
    desc: Run the application
    deps: [ build ]
    cmds:
    - '{{.BUILD_DIR}}/{{.BINARY_NAME}}.exe'

  run-external:
    desc: Run the application in a new window
    deps: [ build ]
    cmds:
    - '{{.BUILD_DIR}}/{{.BINARY_NAME}}.exe -external'

  clean:
    desc: Clean build artifacts
    cmds:
    - powershell Remove-Item -Path {{.BUILD_DIR}} -Recurse -Force -ErrorAction Ignore
    - powershell Remove-Item -Path {{.COVERAGE_DIR}} -Recurse -Force -ErrorAction Ignore

  wire:
    desc: Generate wire dependency injection code
    cmds:
    - wire ./...

  all:
    desc: Run all main tasks
    cmds:
    - task: fmt
    - task: wire
    - task: lint
    - task: test
    - task: build

  ci:
    desc: Run CI pipeline tasks
    deps: [ wire ]
    cmds:
    - task: lint
    - task: test
    - task: build

  watch:
    desc: Watch for changes and rebuild
    cmds:
    - watchexec -r -e go "task build && {{.BUILD_DIR}}\{{.BINARY_NAME}}.exe"

  deps:
    desc: Download and tidy dependencies
    cmds:
    - go mod download
    - go mod tidy
