version: '3'

vars:
  BINARY_NAME: dashboard
  BUILD_DIR: build
  COVERAGE_DIR: coverage

tasks:
  default:
    cmds:
    - task --list-all
    silent: true

  install-tools:
    desc: Install development tools
    cmds:
    - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
    - go install golang.org/x/tools/cmd/goimports@latest
    - go install github.com/google/wire/cmd/wire@latest
    - go install github.com/goreleaser/goreleaser@latest
    - go install github.com/nektos/act@latest

  act:
    desc: Run GitHub Actions locally using act
    cmds:
    - act

  act-release:
    desc: Test the release workflow locally
    cmds:
    - act -W .github/workflows/release.yml --eventpath .github/workflows/release-test-event.json

  act-go:
    desc: Test the Go workflow locally
    cmds:
    - act -W .github/workflows/go.yml

  lint:
    desc: Run golangci-lint
    deps: [ wire ]
    cmds:
    - golangci-lint run ./...

  fmt:
    desc: Format code
    cmds:
    - gofmt -s -w .
    - goimports -w .

  test:
    desc: Run tests with coverage
    deps: [ wire ]
    cmds:
    - powershell New-Item -ItemType Directory -Force -Path {{.COVERAGE_DIR}}
    - go test -race -coverprofile={{.COVERAGE_DIR}}/coverage.out -covermode=atomic ./...
    - go tool cover -html={{.COVERAGE_DIR}}/coverage.out -o {{.COVERAGE_DIR}}/coverage.html

  bench:
    desc: Run benchmark tests
    deps: [ wire ]
    cmds:
    - go test -run=^$ -bench=. -benchmem ./internal/ui/...

  build:
    desc: Build the application
    deps: [ wire ]
    platforms:
    - windows
    - linux
    cmds:
    - |
      {{if eq OS "windows"}}
      powershell -ExecutionPolicy Bypass -File ./scripts/build.ps1 -BuildDir {{.BUILD_DIR}} -BinaryName {{.BINARY_NAME}}
      {{else}}
      chmod +x scripts/build.sh
      ./scripts/build.sh {{.BUILD_DIR}} {{.BINARY_NAME}}
      {{end}}

  run:
    desc: Run the application
    deps: [ build ]
    cmds:
    - '{{.BUILD_DIR}}/windows_amd64/bin/{{.BINARY_NAME}}.exe'

  run-external:
    desc: Run the application in a new window
    deps: [ build ]
    cmds:
    - '{{.BUILD_DIR}}/windows_amd64/bin/{{.BINARY_NAME}}.exe -external'

  clean:
    desc: Clean build artifacts
    cmds:
    - powershell Remove-Item -Path {{.BUILD_DIR}} -Recurse -Force -ErrorAction Ignore
    - powershell Remove-Item -Path {{.COVERAGE_DIR}} -Recurse -Force -ErrorAction Ignore

  wire:
    desc: Generate wire dependency injection code
    cmds:
    - wire ./cmd/dashboard

  all:
    desc: Run all main tasks
    cmds:
    - task: fmt
    - task: wire
    - task: lint
    - task: test
    - task: build

  ci:
    desc: Run CI pipeline tasks
    deps: [ wire ]
    cmds:
    - task: lint
    - task: test
    - task: build

  watch:
    desc: Watch for changes and rebuild
    cmds:
    - watchexec -r -e go "task build && {{.BUILD_DIR}}\{{.BINARY_NAME}}.exe"

  deps:
    desc: Download and tidy dependencies
    cmds:
    - go mod download
    - go mod tidy

  run-debug:
    desc: Run the application with debug output
    deps: [ build ]
    cmds:
    - '{{.BUILD_DIR}}/windows_amd64/bin/{{.BINARY_NAME}}.exe -debug'

  release-test-setup:
    desc: Test cross-compilation setup locally
    cmds:
    - |
      powershell -Command "
        $env:CGO_ENABLED='1'
        $env:CC='gcc'
        $env:GOOS='windows'
        $env:GOARCH='amd64'
        $env:PATH='c:\mingw64\bin;' + $env:PATH
        go build -o build/test.exe ./cmd/dashboard
      "

  release-dry-run:
    desc: Test release process locally without publishing
    deps: [ wire, release-test-setup ]
    cmds:
    - goreleaser release --snapshot --clean --skip=publish,validate

  release-local:
    desc: Test the full release workflow using act
    deps: [ wire ]
    cmds:
    - powershell $env:GITHUB_TOKEN = (gh auth token); act -j release --secret GITHUB_TOKEN=$env:GITHUB_TOKEN -e .github/workflows/release-test-event.json

  release-init:
    desc: Initialize test release event file
    cmds:
    - powershell | $json = @{ ref = 'refs/tags/v0.0.0-test' repository = @{ name = 'dashboard' owner = @{ login = 'jonesrussell' } } } $json | ConvertTo-Json | Set-Content .github/workflows/release-test-event.json
