version: '3'

vars:
  BINARY_NAME: dashboard
  BUILD_DIR: build

tasks:
  default:
    cmds:
      - task: build

  install-deps:
    desc: Install project dependencies
    cmds:
      - go mod download
      - go mod tidy

  lint:
    desc: Run linters
    cmds:
      - golangci-lint run ./...

  test:
    desc: Run tests with coverage
    cmds:
      - go test -v -race -coverprofile=coverage.out ./...
      - go tool cover -html=coverage.out -o coverage.html

  build:
    desc: Build the dashboard binary
    deps: [install-deps]
    cmds:
      - mkdir -p {{.BUILD_DIR}}
      - go build -o {{.BUILD_DIR}}/{{.BINARY_NAME}} ./cmd/dashboard
    sources:
      - ./**/*.go
    generates:
      - {{.BUILD_DIR}}/{{.BINARY_NAME}}

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf {{.BUILD_DIR}}
      - rm -f coverage.out coverage.html

  run:
    desc: Run the dashboard
    deps: [build]
    cmds:
      - ./{{.BUILD_DIR}}/{{.BINARY_NAME}}

  generate:
    desc: Run go generate
    cmds:
      - go generate ./...

  wire:
    desc: Run wire generation
    cmds:
      - wire ./...
