name: Build and Test

on:
  push:
    branches: [ main ]
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
      - '.github/workflows/go.yml'
      - 'build/**'
  pull_request:
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
      - '.github/workflows/go.yml'
      - 'build/**'

jobs:
  prepare:
    runs-on: ubuntu-24.04
    outputs:
      go-cache-key: ${{ steps.go-cache.outputs.cache-key }}
    steps:
      - uses: actions/checkout@v4
      - id: go-cache
        run: echo "cache-key=${{ hashFiles('**/go.sum') }}" >> $GITHUB_OUTPUT

  build:
    needs: [prepare]
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        include:
          - os: windows
            arch: amd64
            artifact: godo.exe
            cc: x86_64-w64-mingw32-gcc
            deps: mingw-w64
          - os: linux
            arch: amd64
            artifact: godo
            cc: gcc
            deps: gcc
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache: true
          cache-dependency-path: go.sum
      
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            pkg-config \
            ${{ matrix.deps }}

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
            ~/go/bin
          key: ${{ runner.os }}-${{ matrix.os }}-${{ matrix.arch }}-go-${{ needs.prepare.outputs.go-cache-key }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.os }}-${{ matrix.arch }}-go-

      - name: Install Wire
        run: go install github.com/google/wire/cmd/wire@latest

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build binary
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
          CC: ${{ matrix.cc }}
        run: task build:${{ matrix.os }}

      - name: Get version
        id: get_version
        run: |
          VERSION=$(git describe --tags --always --dirty)
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: godo-${{ steps.get_version.outputs.version }}-${{ matrix.os }}-${{ matrix.arch }}
          path: bin/${{ matrix.artifact }} 